version = 0.1
[default.deploy.parameters]
stack_name = "lambda-s3-zip"
resolve_s3 = true
s3_prefix = "lambda-s3-zip"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
